### ISSUE TITLE
hopper occasionally does not suck up item

### ISSUE THREAD

**Issue by cgw2023** [PaperMC/Folia#190]
### Expected behavior

hopper suck up item instantly when item goes through its above

### Observed/Actual behavior

hopper occasionally does not suck up item

### Steps/models to reproduce

(translated)
1 place flowing water above a hopper
2 place another hopper below the first hopper and use redstone signal to lock it
3 put 5 set of required item or 1 set of required item in the hopper and fill up the other slot with random full item in the hopper below to make a hopper filter
4 place 1 required item in 1 slot and put other random item in other slot in upper filter

youtube video demonstration:
https://youtu.be/bVUyJSLnCgo

### Plugin and Datapack List
```
AnnouncerPlus, AntiPopup, Attollo, AxInventoryRestore, AxShulkers, BetterRTP, BlockLocker, BlueMap, Chunky, ChunkyBorder
CMILib, CodFrame, CoreProtect, DecentHolograms, DeluxeMenus, DiscordSRV, DragonDropElytra, Essentials, EssentialsChat, EssentialsGeoIP
EssentialsProtect, EssentialsSpawn, FancyNpcs, floodgate, FoliaFlow, GreenChunk, GSit, HeadDrop, Kaiivoid, LuckPerms
Matrix, PlaceholderAPI, PlayerWarps, ProtocolLib, Residence, ShulkerRespawner, spark, TAB-Bridge, Vault, ViaBackwards
ViaVersion, VillagerOptimizer, zAuctionHouseV3
```

### Folia version

This server is running Folia version git-Folia-"3843340" (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 3843340 on dev/1.20.2)

### Other

spigot.yml
```
    ticks-per:
      hopper-transfer: 8
      hopper-check: 1
    hopper-amount: 1
    hopper-can-load-chunks: false
```
paper-world-defaults.yml

```
hopper:
  cooldown-when-full: false
  disable-move-event: false
  ignore-occluding-blocks: false
```
